### ISSUE TITLE
out_vdf Error

### ISSUE THREAD

**Issue by FeyrisTan** [alex47exe/gse_fork#1]
So I created _DEFAULT/0 and 1. I left the 0 folder empty and used this for the 1 folder: [https://github.com/alex47exe/gse_fork/tree/dev/tools/generate_emu_config/_DEFAULT/1/steam_settings](url)

It generates it up to the controller config - then I get this:

````
*** STARTED config for app id 427520 ***

[ ] Found app id on Steam store
[ ] Found product info --- writing to 'app_product_info.json'
[ ] Found app name on Steam store
[ ] __ orig name: 'Factorio'
[ ] __ safe name: 'Factorio'
[ ] Copying preset emu configs to '_OUTPUT/427520' folder
[ ] __ default emu config from '_DEFAULT/0' folder
[ ] __ preset emu config from '_DEFAULT/1' folder
[ ] Found app details --- writing to 'app_details.json'
[ ] Found 13 stats --- writing to 'stats.txt'
[ ] Found 38 achievements --- writing to 'achievements.json'
[ ] Found 76 achievements images --- downloading to '.\steam_settings\img' folder
[ ] Found 30 supported languages --- writing to 'supported_languages.txt'
[ ] Found 1 DLC --- writing to 'configs.app.ini'
[ ] Found 8 depots --- writing to 'depots.txt'
[ ] Found 23 branches --- writing to 'branches.json'
[ ] __ default branch name: public, latest build id: 16022393
[ ] Found controller configs --- generating action sets...
Unexpected error:
cannot access local variable 'out_vdf' where it is not associated with a value
-----------------------
Traceback (most recent call last):

  File "generate_emu_config.py", line 1348, in <module>

  File "generate_emu_config.py", line 1072, in main

UnboundLocalError: cannot access local variable 'out_vdf' where it is not associated with a value
````

**Comment by alex47exe** [comment]
Strange. I thought at first it was because you were running the tool on Linux, but it seems I get the same error on Windows too. Will have to look into it.

I haven't tested the tool on Linux as the helper tools and default configuration are for Windows only. So I forgot to copy the _DEFAULT folders on Linux too, so it will probably error out for all games, even without your error. This is fixed now in latest release.

**Comment by alex47exe** [comment]
Managed to track and fix your error now. Also fixed another controller config related error for "Unknown 9: Awakening":
````
*** STARTED config for app id 1477940 ***

[ ] Found app id on Steam store
[ ] Found product info --- writing to 'app_product_info.json'
[ ] Found app name on Steam store
[ ] __ orig name: 'Unknown 9: Awakening'
[ ] __ safe name: 'Unknown 9 Awakening'
[ ] Cleaning '_OUTPUT\1477940' folder...
[ ] Copying preset emu configs to '_OUTPUT\1477940' folder
[ ] __ default emu config from '_DEFAULT\0' folder
[ ] __ preset emu config from '_DEFAULT\1' folder
[ ] Found app details --- writing to 'app_details.json'
[ ] Found 18 stats --- writing to 'stats.txt'
[ ] Found 38 achievements --- writing to 'achievements.json'
[ ] Found 76 achievements images --- downloading to '.\steam_settings\img' folder
[ ] Found 12 supported languages --- writing to 'supported_languages.txt'
[ ] Found 5 DLCs --- writing to 'configs.app.ini'
[ ] Found 5 depots --- writing to 'depots.txt'
[ ] Found 21 branches --- writing to 'branches.json'
[ ] __ default branch name: public, latest build id: 16069251
[ ] Found controller configs --- generating action sets...
Unexpected error:
string indices must be integers, not 'str'
-----------------------
Traceback (most recent call last):

  File "generate_emu_config.py", line 1348, in <module>

  File "generate_emu_config.py", line 1111, in main

TypeError: string indices must be integers, not 'str'
````
